name: resume_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  google_fonts: ^6.2.1
  text_link: ^1.0.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/project/
    - assets/project/icon/
    - assets/project/screens/
    - assets/courses/
    - assets/courses/icon/
    - assets/courses/screens/
